version: '3.8'

services:
  # fe:
  #   build: ./fe
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - FE_PORT=3000

  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - API_PORT=5000
      - DATABASE_URL=postgres://api:${IAGL_DB_PASSWORD}@db:5432/iagl
      - IAGL_DB_PASSWORD=${IAGL_DB_PASSWORD}

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: ${IAGL_DB_PASSWORD}
      POSTGRES_DB: iagl
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
